---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-olap
  namespace: component
  labels:
    app: clickhouse-olap
spec:
  type: ClusterIP
  ports:
  - port: 9000
    name: rpc
  - port: 8123
    name: rest
  - port: 9009
    name: interserver
  - port: 9116
    name: metrics
  clusterIP: None
  selector:
    app: clickhouse-olap
