apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse-olap
  namespace: component
  labels:
    app: clickhouse-olap
spec:
  replicas: 4
  serviceName: clickhouse-olap
  selector:
    matchLabels:
      app: clickhouse-olap
  template:
    metadata:
      labels:
        app: clickhouse-olap
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      nodeSelector:
        viper.sensetime.com/node-data-fusion: "True"
      containers:
        - name: clickhouse-server
          image: 44.44.6.53:5000/infra/yandex/clickhouse-server:20.3.19-v1.1.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
          args:
            - /pre_init.sh && /entrypoint.sh
          env:
          - name: CLICKHOUSE_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: password-secrets
                key: clickhouse_admin_username
          - name: CLICKHOUSE_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-secrets
                key: clickhouse_admin_password
          - name: KAFKA_USERNAME
            valueFrom:
              secretKeyRef:
                name: password-secrets
                key: kafka_admin_username
          - name: KAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-secrets
                key: kafka_admin_password
          ports:
          - name: rpc
            containerPort: 9000
            protocol: TCP
          - name: rest
            containerPort: 8123
            protocol: TCP
            hostPort: 31181
          - name: interserver
            containerPort: 9009
            protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: "20Gi"
            limits:
              cpu: "16"
              memory: "90Gi"
          volumeMounts:
          - name: clickhouse-data
            mountPath: /var/lib/clickhouse
          - name: clickhouse-configd
            mountPath: /etc/clickhouse-server/config.xml
            subPath: config.xml
          - name: clickhouse-configd
            mountPath: /etc/clickhouse-server/config.d/remote_servers.xml
            subPath: remote_servers.xml
          - name: clickhouse-configd
            mountPath: /etc/clickhouse-server/config.d/zookeeper.xml
            subPath: zookeeper.xml
          - name: clickhouse-configd
            mountPath: /tmp/clickhouse/users.xml
            subPath: users.xml
          - name: clickhouse-configd
            mountPath: /tmp/clickhouse/extern_redis_config.xml
            subPath: extern_redis_config.xml
          - name: clickhouse-configd
            mountPath: /tmp/clickhouse/kafka.xml
            subPath: kafka.xml
          - name: clickhouse-configd
            subPath: "pre_init.sh"
            mountPath: /pre_init.sh
            readOnly: true
          - name: clickhouse-configd
            subPath: "init_component.sh"
            mountPath: /init_component.sh
            readOnly: true
        - name: clickhouse-exporter
          image: 44.44.6.53:5000/infra/f1yegor/clickhouse-exporter:latest
          imagePullPolicy: IfNotPresent
          command:
            - 'sh'
            - '-c'
            - '/usr/local/bin/clickhouse_exporter'
          ports:
          - name: metrics
            containerPort: 9116
            protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
          - name: CLICKHOUSE_USER
            valueFrom:
              secretKeyRef:
                name: password-secrets
                key: clickhouse_admin_username
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password-secrets
                key: clickhouse_admin_password
      volumes:
        - name: clickhouse-configd
          configMap:
            name: clickhouse-configd
            defaultMode: 0755
  podManagementPolicy: Parallel
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "storageclass-local-clickhouse"
      resources:
        requests:
          storage: 10G
