kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Values.heanlessService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  selector:
    {{- include "rabbitmq-cluster.selectorLabels" . | nindent 4}}
