kind: Secret
apiVersion: v1
metadata:
  name: rmq-cluster-secret
  namespace: {{ .Release.Namespace }}
stringData:
  cookie: ERLANG_COOKIE
  password: RABBITMQ_PASS
  url: amqp://RABBITMQ_USER:RABBITMQ_PASS@{{ .Values.heanlessService.name }}
  username: RABBITMQ_USER
type: Opaque
