replicaCount: 1

updateStrategy: {}

imagePullSecretName:

image:
  repository: jfelten/openvpn-docker
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  externalIPs: []
  nodePort: 32085

  annotations: {}
podAnnotations: {}

ipForwardInitContainer: false

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 128Mi

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 2

persistence:
  enabled: true

  storageClass: "vpn-nfs-sc"
  accessMode: ReadWriteOnce
  size: 1024M
openvpn:
  OVPN_NETWORK: 10.240.0.0
  OVPN_SUBNET: 255.255.0.0
  OVPN_PROTO: udp
  OVPN_K8S_POD_NETWORK: "172.16.0.0"
  OVPN_K8S_POD_SUBNET: "255.255.0.0"
  OVPN_K8S_SVC_NETWORK: "10.96.0.0"
  OVPN_K8S_SVC_SUBNET: "255.255.0.0"
  DEFAULT_ROUTE_ENABLED: true
  dhcpOptionDomain: true
  redirectGateway: true
  useCrl: false
  taKey: false


  istio:
    enabled: false
    proxy:
      port: 15001
  iptablesExtra: []

  ccd:
    enabled: false
    config: {}
cipher: AES-256-CBC
nodeSelector: {}
tolerations: []
