apiVersion: v1
kind: Service
metadata:
  name: infra-mysql
  namespace: infra
  labels:
    app: infra-mysql
spec:
  ports:
  - port: 3306
    targetPort: dbport
  selector:
    app: infra-mysql
    tier: mysql