apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: infra-zk-sc
  namespace: infra
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: infra-zk-sc
  local:
    path: /admin/zookeeper/  # 节点上的目录
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - zookeeper