apiVersion: v1
kind: Service
metadata:
  name: zk-test1
  namespace: infra
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: zookeeper
spec:
  type: NodePort
  sessionAffinity: None
  ports:
    - name: tcp-client
      port: 2181
      targetPort: client
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: zookeeper
