apiVersion: v1
kind: Service
metadata:
  labels:
    app: zkui
  name: rocketmq-dashboard
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: port
    nodePort: 30809
  selector:
    app: zkui
