apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: infra
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:          # 滚动更新配置
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.8.33-management
        name: rebbitmd
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
          name: web
          protocol: TCP
        env:                # 环境变量, 其他支持的环境变量查看hub.docker官网镜像简介
        - name: TZ
          value: Asia/Shanghai
        - name: LANG
          value: C.UTF-8
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: root123
        lifecycle: {}       #  生命周期配置
        livenessProbe:      #  健康检查
          failureThreshold: 2
          initialDelaySeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5672
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 2
          initialDelaySeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5672
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 998m
            memory: 1019Mi
          requests:
            cpu: 998m
            memory: 1019Mi
      affinity: {}              # 亲和性配置
      dnsPolicy: ClusterFirst   # 采用集群DNS 默认就是这个
      restartPolicy: Always     # Pod重启策略